### ISSUE TITLE
send/receive/record player orientation

### ISSUE THREAD

**Issue by akoehn** [minecraft-saar/infrastructure#9]
We need to know the participants' rotation to correctly utter "right", "left", etc.

**Comment by akoehn** [comment]
@ca-schaefer If I understand correctly, the orientation is now part of the status messages.

- Can you document what they mean (what does 0 mean, is it degrees, radians, or something else)?
 - It looks like there are three numbers (xdir, ydir, zdir); do we actually need three?  I assume that the viewpoint can only be rotated along two axes.

**Comment by ca-schaefer** [comment]
afaik, Minecraft offers two ways of representing the direction a player is facing:

1) Through Location **.getDirection()**
It returns a unit-vector that points into the direction that the Location (in this case the player's eyes) is facing. This is the current implementation (since  cb78e7b)

2) Through combining **.getYaw()** and **.getPitch()**
.getYaw() returns a degree with according to the Bukkit documentation ([https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Location.html#getYaw--)](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Location.html#getYaw--)):

-  0 and 360: positive z, x=0
- 180: negative z, x=0
- 90: negative x, z=0
- 270: positive x, z=0

There is also a visualization in [this forum post](https://www.spigotmc.org/threads/player-direction.175482/#post-1854058)

.getPitch() returns a degree with:

-  0: forward, y=0
-  90 downward, y<0
-  -90 upward, y>0
 
 If I understand the documentation correctly, yaw values should be positive and between 0 and 360 but the plugin returns values between -360 and +360. Thus, the same direction has different values depending on from which side you turned.

The debug screen of Minecraft shows normalized yaw values between -180 and 180 (e.g. normalized 172.8 = raw -187.2). The Spigot-API also has a method to normalize yaw values so that they are consistent with the debug screen.

If we use yaw and pitch instead of direction vectors, I would suggest using the normalized versions of both. Then there would be also the question whether the conversion to planner-friendly positive numbers happens in the plugin (so it sends normalizedYaw + 180 and normalizedPitch + 90) or just before the planner.

Additional question: Should we use player.Location() or player.EyeLocation()?
They should differ only in their y-value where EyeLocation is 1.62m higher than Location.

**Comment by akoehn** [comment]
Thanks for the explanation!  The unit vector is fine and probably easier to work with.  Can you add a one line comment to the protocol definition?

Re Location vs EyeLocation: Each is fine, but again a comment in the protocol definition would be great.

There is no need to normalize the direction values so that they are larger than zero.  This is only a problem with objects in the world and from the planning perspective, the user is not an object of the world.

**Comment by ca-schaefer** [comment]
added comments in 234e619
